### ISSUE TITLE
Optimize memory usage / profiling investigation

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/minian#33]
Some parts of the pipeline consume a lot of RAM (memory) causing the Jupyter notebook kernel to crash. 

for example this step:
**visualization**
`generate_videos(minian, varr, dpath, param_save_minian['fname'] + ".mp4", scale='auto')`

**Comment by gidili** [comment]
@zsinnema should we close this or still ongoing?

**Comment by zsinnema** [comment]
![output](https://user-images.githubusercontent.com/124044/84806537-28dbb080-b006-11ea-8a79-fa8a2a00e9fe.png)

after running ```
python -m cProfile -o pipeline.cprofiler.pstats pipeline.py
gprof2dot -f pstats pipeline.cprofiler.pstats | dot -Tpng -o output.png && eog output.png
```
