### ISSUE TITLE
Freeze environment.yml

### ISSUE THREAD

**Issue by wmau** [MetaCell/minian#42]
People are still running into environment issues like [here](https://github.com/DeniseCaiLab/minian/issues/57). We need to lock package versions in the environment.yml.

**Comment by zsinnema** [comment]
My conclusion after investigation the environment.yaml is that the env.yaml is correctly configure. Therefore I think the end user did a pip upgrade or conda update which caused an update of the scikit-learn module. 

For now no change/fix is needed

**Comment by gidili** [comment]
@wmau just calling your attention to this so you are aware
