### ISSUE TITLE
Fix black errors in travis build

### ISSUE THREAD

**Issue by phildong** [MetaCell/minian#57]
Currently the travis build would fail, and it seems black is behind this. See logs here: https://travis-ci.org/github/DeniseCaiLab/minian/builds/697624646

Can we ask black to spit out something like a "format quality score" instead of complaining and wanting to re-format all the scripts?

**Comment by gidili** [comment]
Hi @phildong I think given that it would take 1-2 hours to sort out all the formatting (@zsinnema can confirm) it might make more sense to bite the bullet and do it given that we now have some comparables of data set runs to make sure we are not breaking obvious things. The most important advantage of using a linter is that it spots potential errors and suspicious thing, and overall increases code quality for maintainability making it easier for developers to jump on the codebase in the future. From experience, if we take away the discomfort of the build failing it's one of those things you'd end up ignoring in the long run. We actively enforce this on all of our projects, and even though the final decision rests with you I would strongly suggest we prioritise this in the next sprint given the very modest investment of hours 🙂

**Comment by gidili** [comment]
I would suggest repurposing this card to "re-format codebase for black compliance"

**Comment by gidili** [comment]
Repurposed after the discussion at the sprint meeting today
