### ISSUE TITLE
Code coverage badge

### ISSUE THREAD

**Issue by gidili** [MetaCell/minian#60]

**Comment by zsinnema** [comment]
@phildong can you please create an account here: https://codecov.io/
and set the default branch to dev
(you can change it in the settings at the right, next to compare)

please let me know when you did it

**Comment by zsinnema** [comment]
and can you please send me the link to the badge

**Comment by phildong** [comment]
here is the md code!
```markdown
[![codecov](https://codecov.io/gh/DeniseCaiLab/minian/branch/master/graph/badge.svg)](https://codecov.io/gh/DeniseCaiLab/minian)
```
it also talks about some report token but it says not required for travis. Let me know if you need that too!
