### ISSUE TITLE
Investigate file handles on Windows

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/minian#61]
Investigate how to increase/check file handles in windows

info:
https://docs.microsoft.com/nl-nl/archive/blogs/markrussinovich/pushing-the-limits-of-windows-handles

**Comment by gidili** [comment]
After scouring the internet: 

- Relevant: https://techcommunity.microsoft.com/t5/windows-blog-archive/pushing-the-limits-of-windows-handles/ba-p/723848
- Relevant but not promising (the best answer says it's not possible to increase the limit, just suggest thread optimization): https://stackoverflow.com/questions/31108693/increasing-no-of-file-handles-in-windows-7-64-bit#

**Comment by zsinnema** [comment]
see  #35
