### ISSUE TITLE
Publish to pip / conda preparation steps

### ISSUE THREAD

**Issue by gidili** [MetaCell/minian#83]

**Comment by zsinnema** [comment]
@gidili @phildong
some questions:

- what will be the final license: GNU or MIT
- who will be the author (see https://test.pypi.org/project/MiniAn/0.0.1/)
- do we include the demo movies in the package or do we only leave them in the github repo (I advise to keep the python package clean)
- same for the notebooks, do we include the notebooks or not (I advice not and keep the python package clean)
