### ISSUE TITLE
Question: Does the firing rate of cells impact compute time significantly or is it mainly a question of number of active cells in the field of view?

### ISSUE THREAD

**Issue by gidili** [MetaCell/minian#95]

**Comment by gidili** [comment]
**Context**: This came up in conversations we are having while trying to estimate the compute time (and subsequent cost) that users (other labs that want to use minian online) would incur into if the minian pipeline were to be cloud hosted.

@zsinnema @wmau @phildong do you guys know if the firing rate of cells reflects on compute time per given dataset run through the full pipeline? 

**Related**: Does the toy dataset generator hardcode or randomise firing rate at the moment and does it even matter?

**Comment by wmau** [comment]
I expect the number of neurons plays a larger role than activity rate but I am not actually sure. The basis for my guess is that more neurons equates to a larger data matrix whereas more firing simply means larger values in the matrix.

**Comment by phildong** [comment]
yep agreed with @wmau . The firing timing in the toy dataset is randomized and should not matter in terms of performance

**Comment by gidili** [comment]
Thanks @phildong and @wmau - I also thought so but wanted to confirm 👍
