### ISSUE TITLE
Test minian from conda-forge

### ISSUE THREAD

**Issue by gidili** [MetaCell/minian#97]
End user minian install from conda forge

**Comment by gidili** [comment]
Tested this with these commands MacOS 10.15.6:

```
conda create --name minian
conda activate minian
conda install -c conda-forge minian
minian-install -b dev --notebooks --demo
jupyter notebook
```

I can report success, worked right off the bat:

<img width="1458" alt="Screenshot 2020-10-03 at 19 15 58" src="https://user-images.githubusercontent.com/68134/94998901-47fa5000-05ad-11eb-8d74-364525b8f349.png">

Congrats @zsinnema super easy to use 👍 

@wmau @neuroBazzi can you guys try on your envs?

**Comment by wmau** [comment]
Works on Windows 10 Home 64-bit build 19041.

**Comment by neuroBazzi** [comment]
Works on Mint 18.3 (~ Ubuntu 4)
